name: Enforce English-only content

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  no-chinese-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fail if Chinese characters are present in project files
        run: |
          set -e
          # Search code and docs, exclude dependencies and build outputs
          MATCHES=$(grep -RIl --exclude-dir={node_modules,ios/Pods,android,.git,vendor,build,dist} --include='*.{ts,tsx,js,jsx,json,md,mdx}' '[\u4e00-\u9fff]' || true)
          if [ -n "$MATCHES" ]; then
            echo "Chinese characters detected in the following files:" >&2
            echo "$MATCHES" >&2
            exit 1
          fi
          echo "No Chinese characters found."


